### ISSUE TITLE
Allow X-User-ID in Request

### ISSUE THREAD

**Issue by mheumann** [MethodenDB-YFU/backend#57]
CORS is a bi***. This being said, we need to implement, that X-User-ID is added to the [Access-Control-Allow-Headers](https://developer.mozilla.org/de/docs/Web/HTTP/Headers/Access-Control-Allow-Headers) for POST, PUT and DELETE requests.

**Comment by alexmsenger** [comment]
Implemented in #58.

For Config see [`src/main/resources/application.yaml`](https://github.com/MethodenDB-YFU/backend/blob/master/src/main/resources/application.yml) corresponding key is `cors`.
